name: WTcourse

channels:
  - default
  - conda-forge

dependencies:
  # Base
  - python=3.6
  - pip
  - ipython

  # Jupyter
  - jupyterlab

  # Maths
  - numpy

  # Viz
  - matplotlib

  # MD
  - MDAnalysis
  - nglview

  # Dev
  - flake8
  - black
  - isort
