name: oxpy

channels:
  - default
  - conda-forge

dependencies:
  # Base
  - python=3.6
  - pip
  - ipython

  # Jupyter
  - jupyter

  # Maths
  - numpy

  # Viz
  - matplotlib

  # MD
  - MDAnalysis
  - nglview
