name: oxpy

channels:
  - conda-forge
  - default
dependencies:
  # Base
  - python=3.6
  - pip
  - ipython

  # Jupyter
  - jupyter
  - jupyter_contrib_nbextensions

  # Maths
  - numpy

  # Viz
  - matplotlib

  # MD
  - MDAnalysis
  - nglview
