CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|Q07001|ACHD_HUMAN         ----------MEGPVLTLGLLAALA--VCG-SWGLNEEERLIRHLFQEKGYNKELRPVAH
sp|Q04844|ACHE_HUMAN         ---------MARAPLGVLLLLG-----LLGRGVGKNEELRLYHHLFNN--YDPGSRPVRE
sp|P11230|ACHB_HUMAN         -----------MTPGALLMLLGALGAPLAPGVRGSEAEGRLREKLFSG--YDSSVRPARE
sp|P30926|ACHB4_HUMAN        ---------MRRAPSLVLFFLVALC--GRGNCRVANAEEKLMDDLLNKTRYNNLIRPATS
sp|P32297-1|ACHA3_HUMAN      MALAVSLPLALSPPRLLLLLL--LS--LLPVARASEAEHRLFERLFED--YNEIIRPVAN
sp|P02708-2|ACHA_HUMAN       ---------MEPWPLLLLFSLC-----SAGLVLGSEHETRLVAKLFKD--YSSVVRPVED
                                          *   *  *              : * .*   *:.   *.   **.  

sp|Q07001|ACHD_HUMAN         KEESVDVALALTLSNLISLKEVEETLTTNVWIEHGWTDNRLKWNAEEFGNISVLRLPPDM
sp|Q04844|ACHE_HUMAN         PEDTVTISLKVTLTNLISLNEKEETLTTSVWIGIDWQDYRLNYSKDDFGGIETLRVPSEL
sp|P11230|ACHB_HUMAN         VGDRVRVSVGLILAQLISLNEKDEEMSTKVYLDLEWTDYRLSWDPAEHDGIDSLRITAES
sp|P30926|ACHB4_HUMAN        SSQLISIKLQLSLAQLISVNEREQIMTTNVWLKQEWTDYRLTWNSSRYEGVNILRIPAKR
sp|P32297-1|ACHA3_HUMAN      VSDPVIIHFEVSMSQLVKVDEVNQIMETNLWLKQIWNDYKLKWNPSDYGGAEFMRVPAQK
sp|P02708-2|ACHA_HUMAN       HRQVVEVTVGLQLIQLINVDEVNQIVTTNVRLKQQWVDYNLKWNPDDYGGVKKIHIPSEK
                               : : : . : : :*:.:.* :: : *.: :   * * .*.:.   . . . :.:... 

sp|Q07001|ACHD_HUMAN         VWLPEIVLENNNDGSFQISYSCNVLVYHYGFVYWLPPAIFRSSCPISVTYFPFDWQNCSL
sp|Q04844|ACHE_HUMAN         VWLPEIVLENNIDGQFGVAYDANVLVYEGGSVTWLPPAIYRSVCAVEVTYFPFDWQNCSL
sp|P11230|ACHB_HUMAN         VWLPDVVLLNNNDGNFDVALDISVVVSSDGSVRWQPPGIYRSSCSIQVTYFPFDWQNCTM
sp|P30926|ACHB4_HUMAN        IWLPDIVLYNNADGTYEVSVYTNLIVRSNGSVLWLPPAIYKSACKIEVKYFPFDQQNCTL
sp|P32297-1|ACHA3_HUMAN      IWKPDIVLYNNAVGDFQVDDKTKALLKYTGEVTWIPPAIFKSSCKIDVTYFPFDYQNCTM
sp|P02708-2|ACHA_HUMAN       IWRPDLVLYNNADGDFAIVKFTKVLLQYTGHITWTPPAIFKSYCEIIVTHFPFDEQNCSM
                             :* *::** **  * : :    . ::   * : * **.*:.* * : *.:**** ***::

sp|Q07001|ACHD_HUMAN         KFSSLKYTAKEITLSLKQDAKENRTYPVEWIIIDPEGFTENGEWEIVHRPARVNVDPRAP
sp|Q04844|ACHE_HUMAN         IFRSQTYNAEEVEFTFAVDNDGKTINKID---IDTEAYTENGEWAIDFCPGVIRRHHGGA
sp|P11230|ACHB_HUMAN         VFSSYSYDSSEVSLQTGLGPDGQGHQEIH---IHEGTFIENGQWEIIHKPSRLIQPPGDP
sp|P30926|ACHB4_HUMAN        KFRSWTYDHTEIDMVL-MTPT-----------ASMDDFTPSGEWDIVALPGRRTVNP---
sp|P32297-1|ACHA3_HUMAN      KFGSWSYDKAKIDLVL-IGSS-----------MNLKDYWESGEWAIIKAPGYKHDIKYNC
sp|P02708-2|ACHA_HUMAN       KLGTWTYDGSVVAINPESDQ------------PDLSNFMESGEWVIKESRGWKHSVTYSC
                              : : .*    : :                       :  .*:* *    .         

sp|Q07001|ACHD_HUMAN         L--DSPSRQDITFYLIIRRKPLFYIINILVPCVLISFMVNLVFYLPADS-GEKTSVAISV
sp|Q04844|ACHE_HUMAN         T--DGPGETDVIYSLIIRRKPLFYVINIIVPCVLISGLVLLAYFLPAQAGGQKCTVSINV
sp|P11230|ACHB_HUMAN         RGGREGQRQEVIFYLIIRRKPLFYLVNVIAPCILITLLAIFVFYLPPDA-GEKMGLSIFA
sp|P30926|ACHB4_HUMAN        ---QDPSYVDVTYDFIIKRKPLFYTINLIIPCVLTTLLAILVFYLPSDC-GEKMTLCISV
sp|P32297-1|ACHA3_HUMAN      C---EEIYPDITYSLYIRRLPLFYTINLIIPCLLISFLTVLVFYLPSDC-GEKVTLCISV
sp|P02708-2|ACHA_HUMAN       C--PDTPYLDITYHFVMQRLPLYFIVNVIIPCLLFSFLTGLVFYLPTDS-GEKMTLSISV
                                      :: : : :.* **:: :*:: **:* : :. :.::**.:. *:*  :.* .

sp|Q07001|ACHD_HUMAN         LLAQSVFLLLISKRLPATSMAIPLIGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLS
sp|Q04844|ACHE_HUMAN         LLAQTVFLFLIAQKIPETSLSVPLLGRFLIFVMVVATLIVMNCVIVLNVSQRTPTTHAMS
sp|P11230|ACHB_HUMAN         LLTLTVFLLLLADKVPETSLSVPIIIKYLMFTMVLVTFSVILSVVVLNLHHRSPHTHQMP
sp|P30926|ACHB4_HUMAN        LLALTFFLLLISKIVPPTSLDVPLIGKYLMFTMVLVTFSIVTSVCVLNVHHRSPSTHTMA
sp|P32297-1|ACHA3_HUMAN      LLSLTVFLLVITETIPSTSLVIPLIGEYLLFTMIFVTLSIVITVFVLNVHYRTPTTHTMP
sp|P02708-2|ACHA_HUMAN       LLSLTVFLLVIVELIPSTSSAVPLIGKYMLFTMVFVIASIIITVIVINTHHRSPSTHVMP
                             **: :.**::: . :* **  :*::  :::* *:..   ::  * *:*   *:* ** :.

sp|Q07001|ACHD_HUMAN         EGVKKLFLETLPELLH---MSRPAEDGPSPGALVR-RS---SSLGYISKAEEYFLLKSRS
sp|Q04844|ACHE_HUMAN         PRLRHVLLELLPRLLG----SPPPPEAPRAASPPR-RA---SSVGLLLRAEELILKKPRS
sp|P11230|ACHB_HUMAN         LWVRQIFIHKLPLYLR---LKRPKPERDLMPEPPHCSS---PGSGWGRGTDEYFIRKPPS
sp|P30926|ACHB4_HUMAN        PWVKRCFLHKLPTFLF---MKRPGPDS----SPARAFP---PSKSCVTKPEATATSTSPS
sp|P32297-1|ACHA3_HUMAN      SWVKTVFLNLLPRVMF---MTRPTSNEGNAQKPRPLYGAELSNLNCFSRAESKGCKEGYP
sp|P02708-2|ACHA_HUMAN       NWVRKVFIDTIPNIMFFSTMKRPSREK----QDKKIFT---EDIDI----SDISGKPGPP
                               :.  ::  :*  :     . *  :                . .     .        .

sp|Q07001|ACHD_HUMAN         DL-----MFEKQSERHGLARRLTTARRPPASSE----------QAQQELFNELKPAVDGA
sp|Q04844|ACHE_HUMAN         EL-----VFEGQR------------HRQGTWTAA-------FCQSLGAAAPEVRCCVDAV
sp|P11230|ACHB_HUMAN         DF-----LFPKPN------------RFQPELSAPDLRRFIDGPNRAVALLPELREVVSSI
sp|P30926|ACHB4_HUMAN        NFYGNSMYFVNPA---------SAASKSPAGSTPVAIPRDFWLRSSGRFRQDVQEALEGV
sp|P32297-1|ACHA3_HUMAN      CQDGMCGYCHHRR--------IKISNFSANLTRSSSSESVDAVLSLSALSPEIKEAIQSV
sp|P02708-2|ACHA_HUMAN       PM-----GFHSPL----------------------------------IKHPEVKSAIEGI
                                                                                ::.  :.. 

sp|Q07001|ACHD_HUMAN         NFIVNHMRDQNNYNEEKDSWNRVARTVDRLCLFVVTPVMVVGTAWIFLQGVY--NQPPPQ
sp|Q04844|ACHE_HUMAN         NFVAESTRDQEATGEEVSDWVRMGNALDNICFWAALVLFSVGSSLIFLGAYF--NRVPDL
sp|P11230|ACHB_HUMAN         SYIARQLQEQEDHDALKEDWQFVAMVVDRLFLWTFIIFTSVGTLVIFLDATY--HLPPPD
sp|P30926|ACHB4_HUMAN        SFIAQHMKNDDEDQSVVEDWKYVAMVVDRLFLWVFMFVCVLGTVGLFLPPLFQTHAASEG
sp|P32297-1|ACHA3_HUMAN      KYIAENMKAQNEAKEIQDDWKYVAMVIDRIFLWVFTLVCILGTAGLFLQPLM--AREDA-
sp|P02708-2|ACHA_HUMAN       KYIAETMKSDQESNNAAAEWKYVAMVMDHILLGVFMLVCIIGTLAVFAGRLI--ELNQQG
                             .::.   . ::       .*  :. .:*.: : .   .  :*:  :*             

sp|Q07001|ACHD_HUMAN         PFPGDPYSYNVQDKRFI
sp|Q04844|ACHE_HUMAN         PYAPCIQP---------
sp|P11230|ACHB_HUMAN         PFP--------------
sp|P30926|ACHB4_HUMAN        PYAAQRD----------
sp|P32297-1|ACHA3_HUMAN      -----------------
sp|P02708-2|ACHA_HUMAN       -----------------
                                              
