>P1;sp|Q07001|ACHD_HUMAN/1-517
sp|Q07001|ACHD_HUMAN 517 residues
----------MEGPVLTLGLLAALA--VCG-SWGLNEEERLIRHLFQEKGYNKELRPVAHKEESVDVALALT
LSNLISLKEVEETLTTNVWIEHGWTDNRLKWNAEEFGNISVLRLPPDMVWLPEIVLENNNDGSFQISYSCNV
LVYHYGFVYWLPPAIFRSSCPISVTYFPFDWQNCSLKFSSLKYTAKEITLSLKQDAKENRTYPVEWIIIDPE
GFTENGEWEIVHRPARVNVDPRAPL--DSPSRQDITFYLIIRRKPLFYIINILVPCVLISFMVNLVFYLPAD
S-GEKTSVAISVLLAQSVFLLLISKRLPATSMAIPLIGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLS
EGVKKLFLETLPELLH---MSRPAEDGPSPGALVR-RS---SSLGYISKAEEYFLLKSRSDL-----MFEKQ
SERHGLARRLTTARRPPASSE----------QAQQELFNELKPAVDGANFIVNHMRDQNNYNEEKDSWNRVA
RTVDRLCLFVVTPVMVVGTAWIFLQGVY--NQPPPQPFPGDPYSYNVQDKRFI*
>P1;sp|Q04844|ACHE_HUMAN/1-493
sp|Q04844|ACHE_HUMAN 493 residues
---------MARAPLGVLLLLG-----LLGRGVGKNEELRLYHHLFNN--YDPGSRPVREPEDTVTISLKVT
LTNLISLNEKEETLTTSVWIGIDWQDYRLNYSKDDFGGIETLRVPSELVWLPEIVLENNIDGQFGVAYDANV
LVYEGGSVTWLPPAIYRSVCAVEVTYFPFDWQNCSLIFRSQTYNAEEVEFTFAVDNDGKTINKID---IDTE
AYTENGEWAIDFCPGVIRRHHGGAT--DGPGETDVIYSLIIRRKPLFYVINIIVPCVLISGLVLLAYFLPAQ
AGGQKCTVSINVLLAQTVFLFLIAQKIPETSLSVPLLGRFLIFVMVVATLIVMNCVIVLNVSQRTPTTHAMS
PRLRHVLLELLPRLLG----SPPPPEAPRAASPPR-RA---SSVGLLLRAEELILKKPRSEL-----VFEGQ
R------------HRQGTWTAA-------FCQSLGAAAPEVRCCVDAVNFVAESTRDQEATGEEVSDWVRMG
NALDNICFWAALVLFSVGSSLIFLGAYF--NRVPDLPYAPCIQP---------*
>P1;sp|P11230|ACHB_HUMAN/1-501
sp|P11230|ACHB_HUMAN 501 residues
-----------MTPGALLMLLGALGAPLAPGVRGSEAEGRLREKLFSG--YDSSVRPAREVGDRVRVSVGLI
LAQLISLNEKDEEMSTKVYLDLEWTDYRLSWDPAEHDGIDSLRITAESVWLPDVVLLNNNDGNFDVALDISV
VVSSDGSVRWQPPGIYRSSCSIQVTYFPFDWQNCTMVFSSYSYDSSEVSLQTGLGPDGQGHQEIH---IHEG
TFIENGQWEIIHKPSRLIQPPGDPRGGREGQRQEVIFYLIIRRKPLFYLVNVIAPCILITLLAIFVFYLPPD
A-GEKMGLSIFALLTLTVFLLLLADKVPETSLSVPIIIKYLMFTMVLVTFSVILSVVVLNLHHRSPHTHQMP
LWVRQIFIHKLPLYLR---LKRPKPERDLMPEPPHCSS---PGSGWGRGTDEYFIRKPPSDF-----LFPKP
N------------RFQPELSAPDLRRFIDGPNRAVALLPELREVVSSISYIARQLQEQEDHDALKEDWQFVA
MVVDRLFLWTFIIFTSVGTLVIFLDATY--HLPPPDPFP--------------*
>P1;sp|P30926|ACHB4_HUMAN/1-498
sp|P30926|ACHB4_HUMAN 498 residues
---------MRRAPSLVLFFLVALC--GRGNCRVANAEEKLMDDLLNKTRYNNLIRPATSSSQLISIKLQLS
LAQLISVNEREQIMTTNVWLKQEWTDYRLTWNSSRYEGVNILRIPAKRIWLPDIVLYNNADGTYEVSVYTNL
IVRSNGSVLWLPPAIYKSACKIEVKYFPFDQQNCTLKFRSWTYDHTEIDMVL-MTPT-----------ASMD
DFTPSGEWDIVALPGRRTVNP------QDPSYVDVTYDFIIKRKPLFYTINLIIPCVLTTLLAILVFYLPSD
C-GEKMTLCISVLLALTFFLLLISKIVPPTSLDVPLIGKYLMFTMVLVTFSIVTSVCVLNVHHRSPSTHTMA
PWVKRCFLHKLPTFLF---MKRPGPDS----SPARAFP---PSKSCVTKPEATATSTSPSNFYGNSMYFVNP
A---------SAASKSPAGSTPVAIPRDFWLRSSGRFRQDVQEALEGVSFIAQHMKNDDEDQSVVEDWKYVA
MVVDRLFLWVFMFVCVLGTVGLFLPPLFQTHAASEGPYAAQRD----------*
>P1;sp|P32297-1|ACHA3_HUMAN/1-504
sp|P32297-1|ACHA3_HUMAN 504 residues
MALAVSLPLALSPPRLLLLLL--LS--LLPVARASEAEHRLFERLFED--YNEIIRPVANVSDPVIIHFEVS
MSQLVKVDEVNQIMETNLWLKQIWNDYKLKWNPSDYGGAEFMRVPAQKIWKPDIVLYNNAVGDFQVDDKTKA
LLKYTGEVTWIPPAIFKSSCKIDVTYFPFDYQNCTMKFGSWSYDKAKIDLVL-IGSS-----------MNLK
DYWESGEWAIIKAPGYKHDIKYNCC---EEIYPDITYSLYIRRLPLFYTINLIIPCLLISFLTVLVFYLPSD
C-GEKVTLCISVLLSLTVFLLVITETIPSTSLVIPLIGEYLLFTMIFVTLSIVITVFVLNVHYRTPTTHTMP
SWVKTVFLNLLPRVMF---MTRPTSNEGNAQKPRPLYGAELSNLNCFSRAESKGCKEGYPCQDGMCGYCHHR
R--------IKISNFSANLTRSSSSESVDAVLSLSALSPEIKEAIQSVKYIAENMKAQNEAKEIQDDWKYVA
MVIDRIFLWVFTLVCILGTAGLFLQPLM--AREDA------------------*
>P1;sp|P02708-2|ACHA_HUMAN/1-457
sp|P02708-2|ACHA_HUMAN 457 residues
---------MEPWPLLLLFSLC-----SAGLVLGSEHETRLVAKLFKD--YSSVVRPVEDHRQVVEVTVGLQ
LIQLINVDEVNQIVTTNVRLKQQWVDYNLKWNPDDYGGVKKIHIPSEKIWRPDLVLYNNADGDFAIVKFTKV
LLQYTGHITWTPPAIFKSYCEIIVTHFPFDEQNCSMKLGTWTYDGSVVAINPESDQ------------PDLS
NFMESGEWVIKESRGWKHSVTYSCC--PDTPYLDITYHFVMQRLPLYFIVNVIIPCLLFSFLTGLVFYLPTD
S-GEKMTLSISVLLSLTVFLLVIVELIPSTSSAVPLIGKYMLFTMVFVIASIIITVIVINTHHRSPSTHVMP
NWVRKVFIDTIPNIMFFSTMKRPSREK----QDKKIFT---EDIDI----SDISGKPGPPPM-----GFHSP
L----------------------------------IKHPEVKSAIEGIKYIAETMKSDQESNNAAAEWKYVA
MVMDHILLGVFMLVCIIGTLAVFAGRLI--ELNQQG-----------------*
